-- text2scratch Supabase schema
-- Apply this file in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  email text not null,
  is_banned boolean not null default false,
  banned_reason text,
  banned_at timestamptz,
  last_sign_in_ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_username text not null,
  title text not null default 'Untitled',
  source_text text not null default '',
  share_slug text,
  is_public boolean not null default false,
  ip_address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_bans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text,
  email text,
  reason text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.network_bans (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  reason text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_banned boolean not null default false;
alter table public.profiles add column if not exists banned_reason text;
alter table public.profiles add column if not exists banned_at timestamptz;
alter table public.profiles add column if not exists last_sign_in_ip text;
alter table public.projects add column if not exists owner_username text not null default 'user';
alter table public.projects add column if not exists title text not null default 'Untitled';
alter table public.projects add column if not exists source_text text not null default '';
alter table public.projects add column if not exists share_slug text;
alter table public.projects add column if not exists is_public boolean not null default false;
alter table public.projects add column if not exists ip_address text;
alter table public.projects add column if not exists created_at timestamptz not null default now();
alter table public.projects add column if not exists updated_at timestamptz not null default now();

create unique index if not exists profiles_username_lower_idx on public.profiles (lower(username));
create unique index if not exists profiles_email_lower_idx on public.profiles (lower(email));
create unique index if not exists projects_share_slug_idx on public.projects (share_slug) where share_slug is not null;
create unique index if not exists network_bans_ip_address_idx on public.network_bans (ip_address);
create index if not exists projects_owner_id_idx on public.projects (owner_id);
create index if not exists projects_public_updated_idx on public.projects (is_public, updated_at desc);

create or replace function public.get_client_ip()
returns text
language sql
stable
as $$
  select current_setting('request.headers', true)::json->>'x-forwarded-for';
$$;

create or replace function public.is_network_banned()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.network_bans
    where ip_address = public.get_client_ip()
  ) and not public.is_admin_user();
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.track_project_ip()
returns trigger
language plpgsql
as $$
begin
  new.ip_address = public.get_client_ip();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
before update on public.profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_projects_updated_at on public.projects;
create trigger touch_projects_updated_at
before update on public.projects
for each row
execute function public.touch_updated_at();

drop trigger if exists on_project_ip_track on public.projects;
create trigger on_project_ip_track
before insert or update on public.projects
for each row
execute function public.track_project_ip();

create or replace function public.normalize_username(value text)
returns text
language sql
immutable
as $$
  select left(regexp_replace(lower(trim(coalesce(value, ''))), '[^a-z0-9_]+', '', 'g'), 32);
$$;

create or replace function public.is_admin_user(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from auth.users
    where id = coalesce(check_user_id, auth.uid())
      and lower(email) = 'zhibu378orangetiger707@gmail.com'
  );
$$;

create or replace function public.handle_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  base_username text;
  next_username text;
begin
  base_username := public.normalize_username(
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(coalesce(new.email, ''), '@', 1),
      'user'
    )
  );

  if length(base_username) < 3 then
    base_username := 'user_' || left(replace(new.id::text, '-', ''), 8);
  end if;

  next_username := base_username;

  if exists (
    select 1
    from public.profiles
    where id <> new.id
      and lower(username) = lower(next_username)
  ) then
    next_username := left(base_username, 24) || '_' || left(replace(new.id::text, '-', ''), 6);
  end if;

  insert into public.profiles (id, username, email, last_sign_in_ip)
  values (new.id, next_username, coalesce(new.email, ''), public.get_client_ip())
  on conflict (id) do update
    set email = excluded.email,
        last_sign_in_ip = public.get_client_ip(),
        username = case
          when coalesce(public.profiles.username, '') = '' then excluded.username
          else public.profiles.username
        end,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_profile_sync on auth.users;
create trigger on_auth_user_profile_sync
after insert or update of email, raw_user_meta_data on auth.users
for each row
execute function public.handle_auth_user_profile();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.account_bans enable row level security;
alter table public.network_bans enable row level security;

drop policy if exists bans_admin_all on public.account_bans;
create policy bans_admin_all
on public.account_bans
for all
to authenticated
using (public.is_admin_user());

drop policy if exists network_bans_admin_all on public.network_bans;
create policy network_bans_admin_all
on public.network_bans
for all
to authenticated
using (public.is_admin_user());

drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
on public.profiles
for select
to authenticated
using (auth.uid() = id and not public.is_network_banned());

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
to authenticated
with check (auth.uid() = id and not public.is_network_banned());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles
for update
to authenticated
using (auth.uid() = id and not public.is_network_banned())
with check (auth.uid() = id and not public.is_network_banned());

drop policy if exists projects_select_public_or_owner on public.projects;
create policy projects_select_public_or_owner
on public.projects
for select
to anon, authenticated
using ((is_public or owner_id = auth.uid()) and not public.is_network_banned());

drop policy if exists projects_insert_owner on public.projects;
create policy projects_insert_owner
on public.projects
for insert
to authenticated
with check (owner_id = auth.uid() and not public.is_network_banned());

drop policy if exists projects_update_owner on public.projects;
create policy projects_update_owner
on public.projects
for update
to authenticated
using (owner_id = auth.uid() and not public.is_network_banned())
with check (owner_id = auth.uid() and not public.is_network_banned());

drop policy if exists projects_delete_owner on public.projects;
create policy projects_delete_owner
on public.projects
for delete
to authenticated
using (owner_id = auth.uid() and not public.is_network_banned());

grant select, insert, update on public.profiles to authenticated;
grant select on public.projects to anon, authenticated;
grant insert, update, delete on public.projects to authenticated;

create or replace function public.resolve_login_email(login_identifier text)
returns text
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  normalized_identifier text := lower(trim(coalesce(login_identifier, '')));
  resolved_email text;
begin
  if normalized_identifier = '' then
    return null;
  end if;

  if position('@' in normalized_identifier) > 0 then
    return normalized_identifier;
  end if;

  select lower(coalesce(p.email, u.email))
  into resolved_email
  from auth.users u
  left join public.profiles p on p.id = u.id
  where lower(coalesce(p.username, u.raw_user_meta_data ->> 'username', '')) = normalized_identifier
  limit 1;

  return resolved_email;
end;
$$;

create or replace function public.delete_current_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in.' using errcode = '42501';
  end if;

  delete from auth.users where id = auth.uid();
end;
$$;

create or replace function public.public_project_registry(limit_rows integer default 200)
returns table (
  id uuid,
  title text,
  share_slug text,
  owner_username text,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.title, p.share_slug, p.owner_username, p.updated_at
  from public.projects p
  where p.is_public = true
    and p.share_slug is not null
  order by p.updated_at desc
  limit greatest(1, least(coalesce(limit_rows, 200), 500));
$$;

create or replace function public.admin_list_projects(max_rows integer default 100)
returns table (
  id uuid,
  title text,
  owner_username text,
  is_public boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin_user() then
    raise exception 'Admin privileges required.' using errcode = '42501';
  end if;

  return query
  select p.id, p.title, p.owner_username, p.is_public, p.updated_at
  from public.projects p
  order by p.updated_at desc
  limit greatest(1, least(coalesce(max_rows, 100), 500));
end;
$$;

create or replace function public.admin_restrict_account(identifier text)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  normalized_identifier text := lower(trim(coalesce(identifier, '')));
  target_user_id uuid;
  target_email text;
  target_username text;
begin
  if not public.is_admin_user() then
    raise exception 'Admin privileges required.' using errcode = '42501';
  end if;

  if normalized_identifier = '' then
    raise exception 'Identifier is required.';
  end if;

  select u.id,
         coalesce(p.email, u.email),
         coalesce(p.username, public.normalize_username(u.raw_user_meta_data ->> 'username'))
  into target_user_id, target_email, target_username
  from auth.users u
  left join public.profiles p on p.id = u.id
  where lower(coalesce(p.email, u.email, '')) = normalized_identifier
     or lower(coalesce(p.username, u.raw_user_meta_data ->> 'username', '')) = normalized_identifier
  limit 1;

  if target_user_id is null then
    raise exception 'User not found.';
  end if;

  insert into public.profiles (id, username, email, is_banned, banned_reason, banned_at)
  values (
    target_user_id,
    coalesce(target_username, 'user_' || left(replace(target_user_id::text, '-', ''), 8)),
    coalesce(target_email, ''),
    true,
    'Restricted by admin',
    now()
  )
  on conflict (id) do update
    set is_banned = true,
        banned_reason = 'Restricted by admin',
        banned_at = now(),
        updated_at = now();

  update public.projects
  set is_public = false,
      share_slug = null,
      updated_at = now()
  where owner_id = target_user_id;

  insert into public.account_bans (user_id, username, email, reason, created_by)
  values (target_user_id, target_username, target_email, 'Restricted by admin', auth.uid());

  return target_user_id;
end;
$$;

create or replace function public.admin_network_ban(ip_address text)
returns text
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  normalized_ip text := trim(coalesce(ip_address, ''));
begin
  if not public.is_admin_user() then
    raise exception 'Admin privileges required.' using errcode = '42501';
  end if;

  if normalized_ip = '' then
    raise exception 'IP address or CIDR is required.';
  end if;

  insert into public.network_bans (ip_address, reason, created_by)
  values (normalized_ip, 'Blocked by admin', auth.uid())
  on conflict (ip_address) do update
    set reason = excluded.reason,
        created_by = excluded.created_by,
        created_at = now();

  return normalized_ip;
end;
$$;

grant execute on function public.resolve_login_email(text) to anon, authenticated;
grant execute on function public.get_client_ip() to anon, authenticated;
grant execute on function public.is_network_banned() to anon, authenticated;
grant execute on function public.delete_current_account() to authenticated;
grant execute on function public.public_project_registry(integer) to anon, authenticated;
grant execute on function public.admin_list_projects(integer) to authenticated;
grant execute on function public.admin_restrict_account(text) to authenticated;
grant execute on function public.admin_network_ban(text) to authenticated;
